### PR TITLE
(feat): Add Social Links

### PR DESCRIPTION
**Pull request by theunknownartisthour**
Removed the commit which failed for some reason~

### CODE REVIEW

**Comment by markharding** [comment]
Can you squash to one commit and remove the .gitsubmodule change?

**Comment by theunknownartisthour** [comment]
Sorry about that, forgot I was working on my own master branch for a bit. I'll squash the remaining commits in a second.

**Comment by Andersama** [comment]
@markharding feel free to merge this one at any time*

**Comment by markharding** [comment]
Thanks, we will be sending over a CLA soon.

**Comment by markharding** [comment]
Here's the CLA - https://docs.google.com/document/d/1bFZ1nQhOkvNKxD2ApHKigsFScy3GGQhMYY_batZl8rw/edit?usp=sharing. Once we've got that sorted we are good to push this to production!

**Comment by markharding** [comment]
Thanks, finally merged this. Keep the pull requests coming!

**Pull request closed without merging**
